name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [8.x, 10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Puppeteer Container
        uses: ianwalter/puppeteer@v2.0.0
      - run: npm ci
      - run: npm start &
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: "true"
